# Generated by Django 2.1.5 on 2019-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='thumb',
        ),
        migrations.AddField(
            model_name='playlist',
            name='Image',
            field=models.ImageField(blank=True, default='default.img', upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='music',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
